name: Deploy Functions to DigitalOcean
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_VECTOR_STORE_ID: ${{ secrets.OPENAI_VECTOR_STORE_ID }}
      LOGTAIL_TOKEN: ${{ secrets.LOGTAIL_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies and Test
        run: |
          cd packages/scrapebot/app
          pip install -r requirements.txt
          python -m pytest
          cd ../..
      - name: Install DigitalOcean CLI (doctl)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Connect to Functions Namespace
        run: doctl serverless install && doctl serverless connect shark-fn-namespace
      - name: Deploy Functions
        run: doctl serverless deploy . --remote-build
